const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('markdo', {
  platform: process.platform,
  collapse: (edge) => ipcRenderer.invoke('window:collapse', edge),
  expand: () => ipcRenderer.invoke('window:expand'),
  collapseIfDocked: () => ipcRenderer.invoke('window:collapseIfDocked'),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  close: () => ipcRenderer.invoke('window:close'),
  minimizeCurrent: () => ipcRenderer.invoke('window:minimizeCurrent'),
  closeCurrent: () => ipcRenderer.invoke('window:closeCurrent'),
  hideCurrent: () => ipcRenderer.invoke('window:hideCurrent'),
  setAlwaysOnTop: (value) => ipcRenderer.invoke('window:setAlwaysOnTop', value),
  dragStart: () => ipcRenderer.invoke('window:dragStart'),
  dragEnd: () => ipcRenderer.invoke('window:dragEnd'),
  openNote: (todo) => ipcRenderer.invoke('note:open', todo),
  openImage: (dataUrl) => ipcRenderer.invoke('image:open', dataUrl),
  openDeadlinePicker: (payload) => ipcRenderer.invoke('deadline:open', payload),
  saveNote: (payload) => ipcRenderer.send('note:save', payload),
  saveDeadline: (payload) => ipcRenderer.send('deadline:save', payload),
  setOcrShortcut: (shortcut) => ipcRenderer.invoke('ocr:setShortcut', shortcut),
  setQuickAddShortcut: (shortcut) => ipcRenderer.invoke('quickAdd:setShortcut', shortcut),
  createQuickTodo: (todo) => ipcRenderer.send('quickAdd:createTodo', todo),
  runOcr: () => ipcRenderer.invoke('ocr:capture'),
  finishOcrSelection: (rect) => ipcRenderer.send('ocr:selection', rect),
  cancelOcrSelection: () => ipcRenderer.send('ocr:selection-cancel'),
  onCollapsed: (callback) => ipcRenderer.on('window:collapsed', (_event, state) => callback(state)),
  onClosePopups: (callback) => ipcRenderer.on('window:closePopups', () => callback()),
  onCollapseVisual: (callback) => ipcRenderer.on('window:collapseVisual', (_event, state) => callback(state)),
  onNoteInit: (callback) => ipcRenderer.on('note:init', (_event, todo) => callback(todo)),
  onNoteUpdated: (callback) => ipcRenderer.on('note:updated', (_event, payload) => callback(payload)),
  onDeadlineInit: (callback) => ipcRenderer.on('deadline:init', (_event, payload) => callback(payload)),
  onDeadlineUpdated: (callback) => ipcRenderer.on('deadline:updated', (_event, payload) => callback(payload)),
  onOcrTodo: (callback) => ipcRenderer.on('ocr:todo', (_event, todo) => callback(todo)),
  onOcrStatus: (callback) => ipcRenderer.on('ocr:status', (_event, message) => callback(message)),
  onQuickAddTodo: (callback) => ipcRenderer.on('quickAdd:todo', (_event, todo) => callback(todo)),
  onQuickAdd: (callback) => ipcRenderer.on('quickAdd:focus', () => callback()),
  onQuickAddOpen: (callback) => ipcRenderer.on('quickAdd:open', () => callback())
});
